vocabulary/agile-vocabulary.md
=> agile-vocabulary.md

vocabulary/basic-vocabulary.md
=> basic-vocabulary.md

snippets/README.md, snippets/html-css/contact-form.md, vocabulary/favicon-html.md
=> Adding snippet and vocabulary: ui/ux

vocabulary/ux-design-vocabulary.md
=> adding vocabulary for ux/ui design

randomizer/index.html, randomizer/styles.css
- fixed bug that would nest groups
- styled the randomizer
- added button to copy groups as MD text to clipboard
=> Randomizer improvements ✨

README.md, snippets/html-css/center-everything.md, snippets/html-css/contact-form.md, vocabulary/agile-vocabulary.md, vocabulary/basic-vocabulary.md, vocabulary/favicon-html.md, vocabulary/grid-properties.md, vocabulary/ux-design-terms.md, vocabulary/ux-design-vocabulary.md, vocabulary/web-development-vocabulary.md
Added grid-properties.md
close AlinaTaoRao/AlinaTaoRao.github.io#30
=> Alina added grid-properties.md

.cspell.json, README.md, snippets/html-css/center-everything.md, snippets/html-css/contact-form.md, snippets/html-css/dropdown-menu.md, vocabulary/agile-vocabulary.md, vocabulary/basic-vocabulary.md, vocabulary/favicon-html.md, vocabulary/ux-design-terms.md, vocabulary/ux-design-vocabulary.md, vocabulary/web-development-vocabulary.md
Added dropdown-menu.md snippets
close AlinaTaoRao/AlinaTaoRao.github.io#31
=> Alina added dropdown-menu.md snippets

vocabulary/css-color.md
=> adding css-color to vocabulary

vocabulary/javascript/datatypes.md
=> adding JS Datatypes to vocabulary (added folder javascript under vocabulary)

README.md, admin/data/students.json, randomizer/index.html, randomizer/styles.css, vocabulary/js-variables.md
close lab-antwerp-1/AlinaTaoRao#2
=> Alina added js-variables.md

vocabulary/welcome-to-js.md
=> welcome-to-js-vocabulary.md

snippets/javascript/class-tag-on-scroll.md
=> add js snippet

README.md, vocabulary/javascript/vartypes.md
=> Vocabulary js var

snippets/html-css/resize-div-snippet.md
=> resize-div-snippet.md

snippets/javascript/progress-bar-snippet.md
=> progress-bar-snippet.md

README.md, vocabulary/javascript/js-vocabulary.md
=> adding JS vocabulary

.cspell.json, student-bios/daniel.md
Totally forgot about this one. Just trying to have everything updated.
=> Daniel bio file (Finally 😅 )

README.md, snippets/html-css/resize-div-snippet.md, snippets/javascript/check-if-an-attribute-exists.md, snippets/javascript/progress-bar-snippet.md, student-bios/daniel.md, ux-ui-vocabulary.md, vocabulary/welcome-to-js.md
=> JS Snippet/To check if an attribute with a specified name exists

vocabulary/javascript/js-vocabulary.md
=> update vocabulary/javascript/js-vocabulary.md to include 'lint'

.github/workflows/lint.yml, README.md, package.json, snippets/html-css/resize-div-snippet.md, snippets/javascript/progress-bar-snippet.md, student-bios/daniel.md, ux-ui-vocabulary.md, vocabulary/welcome-to-js.md
Problem: some students use `npm run format`, others don't. 
When changes are add without formatting and then other students add changes with formatting, the **git history** gets **polluted** with whitespace changes. It is the **biggest cause of merge conflicts** for the students. And **makes reviewing PR's harder** because you can't immediately see what's actually changed.
This PR adds checks to see whether all code is formatted properly before merging.
It also fixes previous formatting issues.
=> 👷 Fix formatting + add checks to CI pipeline

README.md, snippets/javascript/caps-lock-on.md, vocabulary/javascript/js-vocabulary.md
Adding JS Snippet: Detect Caps Lock Is On
=> detect-caps-lock-is-on

snippets/javascript/skipping-13.md
Added skipping-13.md with JS snippet: an example of using `continue`.
close lab-antwerp-1/AlinaTaoRao#3
=> Alina: Added skipping-13.md (JS snippet)

snippets/javascript/tryandcatch.md
=> adding snippet try and catch

vocabulary/javascript/parameters-vs-arguments.md
=> Debugging vocabulary 

calendar/index.html, package-lock.json, package.json, snippets/javascript/checked-state-changes.md, vocabulary/javascript/datatypes.md
=> added Snippets

vocabulary/debugging-statements-vs-expressions.md
=> adding debugging vocabulary

snippets/javascript/replace-with-alphabet-position-snippet.md
=> replace-with-alphabet-position-snippet.md

admin/data/coaches.json
=> Added myself to the coaches json

vocabulary/javascript/callback-higher-order.md
=> Alina: callback vs. higher-order function

vocabulary/javascript/error-types.md
=> add error type vocab

.cspell.json, snippets/javascript/classlist-remove-add-toggle-replace.md
=> aviv-snippet-classlist-remove-add-toggle-replace

snippets/javascript/password-rule-checker.md
=> Password rule checker

snippets/html-css/graph-in-markdown.md
=> adding snippet for graph in markdown

vocabulary/debugging-terms.md
=> adding new debugging vocabulary

snippets/javascript/is-prime-snippet.md
=> is-prime-snippet.md

README.md, calendar/index.html, snippets/javascript/replace-with-alphabet-position-snippet.md, vocabulary/javascript/promise-and-promise-states.md
=> aviv; vocab; promise and promise states

snippets/javascript/set-difference.md
=> Alina: Use Set except to get difference

vocabulary/javascript/await.md
=> Alina: asynchronous vocabulary - `await`

snippets/javascript/url-title-path-encodeuri.md
=> Alina: joinedPath vs. encodeURI() when define URL with title
